CREATE DATABASE desafioTMAX;
USE desafioTMAX;

CREATE TABLE Usuario(
	id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    senha VARCHAR(100) NOT NULL
);

CREATE TABLE Livro(
	id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    titulo VARCHAR(200) NOT NULL,
    descricao TEXT NOT NULL,
    reservado TINYINT NOT NULL
);

SELECT * FROM Usuario; where email = 'a@a';
